const model = {
    app: {
        currentPage: 'dailyPage',
    },
    input: {
        dailyPage: {
            checkmark: false,
            date: '23-09-2023',
        },
        weeklyPage: {
            checkmark: false,
            date: '23-09-2023',
        },
        monthlyPage: {
            checkmark: false,
            date: '23-09-2023',
        },
        taskList: {
            priority: '',
            intensity: '',
            date: '',
        },
        taskEdit: {
            edit: false,
            name: 'Vask huset',
            description: '',
            date: '23/09/2023',
            priority: 'høy',
            intensity: 10,
            postpone: 0,
            frequency: '',
            repeat: false,
        },
    },
    data: {
        day: 'monday',
        task: [
            {
                name: 'Vask huset',
                description: '',
                date: '23/09/2023',
                checkmark: false,
                priority: 'høy',
                intensity: 10,
                postpone: 0,
                frequency: '',
                repeat: false,
            },
            {
                name: 'Rydd rommet',
                description: '',
                date: '23/09/2023',
                checkmark: false,
                priority: 'Middels',
                intensity: 5,
                postpone: 0,
                frequency: '',
                repeat: false,
            },
            {
                name: 'Vask vinduene',
                description: '',
                date: '23/09/2023',
                checkmark: false,
                priority: 'Lav',
                intensity: 7,
                postpone: 0,
                frequency: '',
                repeat: false,
            },
            {
                name: 'Mal resten av veggen',
                description: '',
                date: '23/09/2023',
                checkmark: false,
                priority: 'Middels',
                intensity: 8,
                postpone: 0,
                frequency: '',
                repeat: false,
            },
            {
                name: 'Rydd kjøleskapet',
                description: '',
                date: '23/09/2023',
                checkmark: false,
                priority: 'Høy',
                intensity: 2,
                postpone: 0,
                frequency: '',
                repeat: false,
            },
            {
                name: 'Støvsuge trappa',
                description: '',
                date: '23/09/2023',
                checkmark: false,
                priority: 'Høy',
                intensity: 2,
                postpone: 0,
                frequency: '',
                repeat: false,
            },
            {
                name: '',
                description: '',
                date: '23/09/2023',
                checkmark: false,
                priority: '',
                intensity: 0,
                postpone: 0,
                frequency: '',
                repeat: false,
            },
        ],
    },
};